Define new syntax regions for advanced highlighting
rhysd/conflict-marker.vim pull request #7
Opened 2019-09-11 19:31 UTC by gbcreation

This PR offers to define additional syntax regions allowing to further customize the highlighting of the different parts of a conflict.

New syntax regions are:
- **ConflictMarkerBegin:** allows to use a specific highlighting for the begin marker of a conflict (`<<<<<<<`)
- **ConflictMarkerOurs:** allows to use a specific highlighting for the part between the begin marker and the separator marker
- **ConflictMarkerSeparator:** allows to use a specific highlight for the separator marker of a conflict (`=======`)
- **ConflictMarkerTheirs:** allows to use a specific highlighting for the part between the separator marker and the end marker
- **ConflictMarkerEnd:** allows to use a specific highlight for the end marker of a conflict (`>>>>>>>`)

By default the highlight of the **ConflictMarkerBegin**, **ConflictMarkerSeparator** and **ConflictMarkerEnd** regions are a link to the group defined by `g:conflict_marker_highlight_group` to be compatible with the existing highlighting behavior.

To customize the highlighting of the different parts of a conflict, set `g:conflict_marker_highlight_group` to `''` and define the highlighting of the desired parts.

**Example**

```vim
" disable default highlight links to g:conflict_marker_highlight_group
let g:conflict_marker_highlight_group = ''

" Include text after begin and end markers
let g:conflict_marker_begin = '^<<<<<<< .*$'
let g:conflict_marker_end   = '^>>>>>>> .*$'

highlight ConflictMarkerBegin guibg=#2f7366
highlight ConflictMarkerOurs guibg=#2e5049
highlight ConflictMarkerTheirs guibg=#344f69
highlight ConflictMarkerEnd guibg=#2f628e
```

**Result**

![Screenshot_20190911_212653](https://user-images.githubusercontent.com/454315/64728297-f8953d80-d4da-11e9-9033-df5bfdee2f7a.png)

2019-09-12 02:15 UTC, rhysd requested changes
Implementation looks good. Would you update tests and mention these highlight groups in README.md  also?

- https://github.com/rhysd/conflict-marker.vim/blob/master/t/syntax_spec.vim
- https://github.com/rhysd/conflict-marker.vim/blob/master/README.md

2019-09-14 14:45 UTC, gbcreation commented
README and tests updated.

2019-09-14 16:51 UTC, rhysd approved these changes

2019-09-14 16:51 UTC, rhysd commented
Thank you for the updates. I confirmed that CI failure is not related to this PR.

2019-09-14 16:51 UTC, merged

2019-09-14 17:41 UTC, gbcreation commented
Thank you for accepting the PR.
As there is a screenshot in README now, maybe issue #4 can be closed ;)